apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-azuredisk
  labels:
    app: statefulsetwithazuredisk
spec:
  serviceName: statefulset-azuredisk
  replicas: 3
  template:
    metadata:
      labels:
        app: statefulsetwithazuredisk
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: statefulset-azuredisk1
          image: nginx
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/azuredisk
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: statefulsetwithazuredisk
  volumeClaimTemplates:
  - metadata:
      name: persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #      storageClassName: "ultra-disk-sc"
      storageClassName: "managed-premium"
      resources:
        requests:
          storage: 4Gi
